const express = require('express')
const app = express()
const servicePageOM = require('./servicePageOM.js')
const infoDetail = require('./infoDetail.js')
const productDetail = require('./productDetail.js')
const register = require('./register.js')
const plans = require('./plans.js')
const contactUs = require('./contactUs.js')
const services = require('./services.js')
const servicePage2 = require('./servicePage2.js')
const sample = require('./sample.js')
app.get('/',(req,res)=>{
    res.send("This is Home Page")
})
app.use('/infoDetails',infoDetail)
app.use('/productDetail',productDetail)
app.use('/plans',plans)
app.use('/register',register)
app.use('/contactUs',contactUs)
app.use('/services',services)
app.use('/servicePage2',servicePage2)
app.use('/sample',sample)
app.use('/servicePageOM',servicePageOM)
app.listen(1500)